# Generated by Django 2.0.5 on 2018-05-29 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoThisWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(default=0)),
                ('number2', models.IntegerField(default=0)),
                ('number3', models.IntegerField(default=0)),
                ('number4', models.IntegerField(default=0)),
                ('number5', models.IntegerField(default=0)),
                ('number6', models.IntegerField(default=0)),
                ('isWin', models.IntegerField(default=0)),
                ('createDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
